@startuml
' Participants (modules)
actor "User" as User
participant "Main" as Main
participant "Servo" as Servo
participant "USART_COMM" as USART

title Scénario: Mode 2 - Consigne utilisateur

User -> USART: Envoie "mode2"
USART -> Main: Notification de commande
Main -> Main: Passe en MODE2
Main -> USART: sendMessage("Mode 2 activated...")
Main -> Main: Allume LED_VERT_Pin

User -> USART: Envoie valeur "8"
USART -> Main: Notification de valeur
Main -> Main: servoPosition = 8
Main -> USART: sendMessage("Servo position set to 8")
Main -> Servo: Servo_ValueToPosition(8)
Main -> Servo: Servo_SetPosition(position)
@enduml